// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://essutxtnsytcwtjsuztd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVzc3V0eHRuc3l0Y3d0anN1enRkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQxNzQyNzEsImV4cCI6MjA1OTc1MDI3MX0.pP6QNs3hVlc3ts5zpfJG6yt0YxFRHKC-v4CKKGYlMUQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);